const express=require("express");const AdmZip=require("adm-zip");const fs=require("fs");const path=require("path");const os=require("os");
const app=express(),PORT=process.env.PORT||3000,MAX_MB=Number(process.env.MAX_DOWNLOAD_MB||500),MAX_BYTES=MAX_MB*1024*1024;
app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(__dirname,"public")));
app.get("/health",(req,res)=>res.json({ok:true,project:"furia-mods-ia",version:"3.0.0",mediafireResolver:true}));
function disp(v){if(!v)return null;const m=v.match(/filename\*?=(?:UTF-8''|")?([^";\r\n]+)/i);return m?decodeURIComponent(m[1].replace(/^"|"$/g,"")):null}
function isZip(ct,url,name=""){return `${ct||""} ${url||""} ${name||""}`.toLowerCase().includes("zip")||/\.zip(?:$|[?#])/i.test(url||"")||/\.zip$/i.test(name||"")}
async function resolveMediaFire(url){const r=await fetch(url,{redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 (Android) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36"}});if(!r.ok)throw Error(`Não foi possível acessar o link (HTTP ${r.status}).`);const final=r.url,ct=r.headers.get("content-type")||"";if(isZip(ct,final))return{downloadUrl:final,filename:disp(r.headers.get("content-disposition"))};const html=await r.text(),cs=[];
const patterns=[/href=["']([^"']+)["'][^>]*class=["'][^"']*download[^"']*["']/gi,/href=["']([^"']+)["'][^>]*id=["'][^"']*download[^"']*["']/gi,/aria-label=["'][^"']*download[^"']*["'][^>]*href=["']([^"']+)["']/gi,/https?:\/\/[^"'\\\s<>]+/gi];
for(const re of patterns){let m;while((m=re.exec(html))!==null){const c=m[1]||m[0];try{const u=new URL(c,final).toString();if(!cs.includes(u))cs.push(u)}catch{}}}
const ordered=[...cs.filter(u=>/download|mediafire|\.zip/i.test(u)),...cs];
for(const u of ordered){try{const h=await fetch(u,{method:"HEAD",redirect:"follow",headers:{"User-Agent":"Mozilla/5.0"}}),hct=h.headers.get("content-type")||"",cd=h.headers.get("content-disposition")||"";if(h.ok&&(isZip(hct,h.url,cd)||/\.zip(?:$|[?#])/i.test(h.url)))return{downloadUrl:h.url,filename:disp(cd)}}catch{}}
for(const u of ordered){try{const h=await fetch(u,{redirect:"follow",headers:{"User-Agent":"Mozilla/5.0","Range":"bytes=0-0"}}),hct=h.headers.get("content-type")||"",cd=h.headers.get("content-disposition")||"";if(h.ok&&(isZip(hct,h.url,cd)||/\.zip(?:$|[?#])/i.test(h.url))){try{await h.body?.cancel()}catch{}return{downloadUrl:h.url,filename:disp(cd)} }try{await h.body?.cancel()}catch{}}catch{}}
throw Error("Não encontrei o download do ZIP nessa página do MediaFire.")}
async function resolveDownload(url){const p=new URL(url);if(p.hostname.toLowerCase().includes("mediafire.com"))return resolveMediaFire(url);const r=await fetch(url,{redirect:"follow",headers:{"User-Agent":"Mozilla/5.0"}}),ct=r.headers.get("content-type")||"",cd=r.headers.get("content-disposition")||"";if(!r.ok)throw Error(`Falha ao acessar o link (HTTP ${r.status}).`);if(isZip(ct,r.url,cd))return{downloadUrl:r.url,filename:disp(cd)};throw Error("O link não entregou um ZIP diretamente. Links de página são suportados automaticamente para MediaFire.")}
async function downloadFile(url,target){const r=await fetch(url,{redirect:"follow",headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw Error(`Falha no download (HTTP ${r.status}).`);const len=Number(r.headers.get("content-length")||0);if(len>MAX_BYTES)throw Error(`O arquivo excede o limite de ${MAX_MB} MB.`);const f=fs.createWriteStream(target);let total=0;try{for await(const chunk of r.body){total+=chunk.length;if(total>MAX_BYTES){f.destroy();throw Error(`O arquivo excede o limite de ${MAX_MB} MB.`)}if(!f.write(chunk))await new Promise(x=>f.once("drain",x))}f.end();await new Promise((x,y)=>{f.on("finish",x);f.on("error",y)})}catch(e){f.destroy();throw e}return{bytes:total}}
function analyzeZip(file){const z=new AdmZip(file),es=z.getEntries(),files=es.filter(e=>!e.isDirectory),names=files.map(e=>e.entryName),find=re=>names.find(n=>re.test(path.basename(n)))||null,meta=find(/^meta\.xml$/i),read=find(/^(readme|leia[-_ ]?me)(\.[^.]+)?$/i),imgs=files.filter(e=>/\.(png|jpe?g|webp|gif)$/i.test(e.entryName)),texts=files.filter(e=>/\.(txt|md|xml|json|cfg|ini|lua|js)$/i.test(e.entryName));let metaText="",readText="";try{if(meta)metaText=z.readAsText(meta).slice(0,20000)}catch{}try{if(read)readText=z.readAsText(read).slice(0,20000)}catch{}return{fileCount:files.length,directoryCount:es.length-files.length,totalUncompressedBytes:files.reduce((s,e)=>s+(e.header?.size||0),0),images:imgs.map(e=>e.entryName).slice(0,30),metaXml:meta?metaText:null,readme:read?readText:null,textFiles:texts.map(e=>e.entryName).slice(0,50),topLevel:[...new Set(names.map(n=>n.split("/")[0]).filter(Boolean))].slice(0,50)}}
function preview(name,a){return{titulo:name.replace(/\.zip$/i,"").replace(/[_-]+/g," ").trim()||"Mod sem título identificado",descricao:"Descrição será preenchida a partir das informações encontradas no mod.",autor:"Identificar no arquivo",comandos:"Identificar no arquivo",peso:`${(a.totalUncompressedBytes/1024).toFixed(1)} KB`,imagem:a.images[0]||null}}
app.post("/api/analyze",async(req,res)=>{const source=String(req.body?.url||"").trim();if(!source)return res.status(400).json({ok:false,error:"Informe o link do mod."});let tmp=null;try{new URL(source);const r=await resolveDownload(source),name=r.filename||new URL(r.downloadUrl).pathname.split("/").pop()||"mod.zip";if(!/\.zip$/i.test(name)&&!/\.zip(?:$|[?#])/i.test(r.downloadUrl))throw Error("O download encontrado não parece ser um arquivo ZIP.");tmp=path.join(os.tmpdir(),`furia-${Date.now()}-${Math.random().toString(16).slice(2)}.zip`);const d=await downloadFile(r.downloadUrl,tmp),a=analyzeZip(tmp);res.json({ok:true,version:"3.0.0",sourceUrl:source,downloadUrl:r.downloadUrl,file:{name,bytes:d.bytes,sizeMB:+(d.bytes/1024/1024).toFixed(2)},analysis:a,preview:preview(name,a)})}catch(e){console.error(e);res.status(400).json({ok:false,error:e.message||"Não foi possível analisar o mod."})}finally{if(tmp)try{fs.unlinkSync(tmp)}catch{}}});
app.listen(PORT,()=>console.log(`Fúria Mods IA V3.0 rodando na porta ${PORT}`));
