const express=require('express');const AdmZip=require('adm-zip');const path=require('path');const fs=require('fs');const os=require('os');const crypto=require('crypto');
const app=express();const PORT=process.env.PORT||3000;const MAX_DOWNLOAD_MB=Number(process.env.MAX_DOWNLOAD_MB||500);const MAX_DOWNLOAD_BYTES=MAX_DOWNLOAD_MB*1024*1024;
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));const jobs=new Map();
function safeName(n){return String(n||'arquivo').replace(/[^\w.\- ]+/g,'_').slice(0,120)}
function validUrl(v){try{const u=new URL(v);return u.protocol==='http:'||u.protocol==='https:'}catch{return false}}
function looksZip(p,u){if(/\.zip(?:[?#].*)?$/i.test(u))return true;try{const h=fs.readFileSync(p).subarray(0,4).toString('hex');return ['504b0304','504b0506','504b0708'].includes(h)}catch{return false}}
async function download(url,target){const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'FuriaModsIA/2.0'}});if(!r.ok)throw new Error(`Download recusado pelo servidor: HTTP ${r.status}`);const len=Number(r.headers.get('content-length')||0);if(len>MAX_DOWNLOAD_BYTES)throw new Error(`Arquivo maior que o limite atual de ${MAX_DOWNLOAD_MB} MB.`);const out=fs.createWriteStream(target);const rd=r.body.getReader();let total=0;try{while(true){const {done,value}=await rd.read();if(done)break;total+=value.byteLength;if(total>MAX_DOWNLOAD_BYTES)throw new Error(`Arquivo maior que o limite atual de ${MAX_DOWNLOAD_MB} MB.`);if(!out.write(Buffer.from(value)))await new Promise(x=>out.once('drain',x))}}finally{out.end()}await new Promise((res,rej)=>{out.on('finish',res);out.on('error',rej)});return total}
function analyze(p){const z=new AdmZip(p),es=z.getEntries(),files=es.filter(e=>!e.isDirectory).map(e=>({name:e.entryName,size:e.header.size,compressedSize:e.header.compressedSize}));return{archiveType:'zip',totalEntries:es.length,totalFiles:files.length,totalBytes:files.reduce((s,f)=>s+f.size,0),images:files.filter(f=>/\.(png|jpe?g|webp|gif)$/i.test(f.name)).slice(0,12),meta:files.find(f=>/(^|\/)meta\.xml$/i.test(f.name))||null,readmes:files.filter(f=>/(^|\/)(readme|leia-me|leia_me|credits|creditos)[^/]*\.(txt|md|nfo)$/i.test(f.name)).slice(0,10),interestingText:files.filter(f=>/\.(txt|md|nfo|xml|json|cfg|lua)$/i.test(f.name)).slice(0,40),topLevel:[...new Set(files.map(f=>f.name.split('/')[0]))].slice(0,30),files:files.slice(0,200)}}
app.get('/health',(q,s)=>s.json({ok:true,project:'furia-mods-ia',version:'2.0.0'}));
app.post('/api/analyze-url',async(req,res)=>{const url=String(req.body?.url||'').trim();if(!validUrl(url))return res.status(400).json({ok:false,error:'Informe uma URL http/https válida.'});const id=crypto.randomUUID(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'furia-mods-')),file=path.join(dir,'mod-download');jobs.set(id,{id,status:'baixando',url,createdAt:new Date().toISOString()});try{const bytes=await download(url,file);if(!looksZip(file,url))throw new Error('Nesta primeira versão, a análise automática aceita arquivos ZIP. RAR/7Z serão adicionados depois.');const analysis=analyze(file);const base=safeName(path.basename(new URL(url).pathname).replace(/\.[^.]+$/,'')).replace(/[_-]+/g,' ').trim()||'Novo mod';const result={ok:true,id,status:'analisado',source:{url,bytes},analysis,post:{titulo:base,descricao:'Aguardando análise de conteúdo.',autor:'Não identificado',categoria:'Não identificada',comandos:'Não identificados',peso:`${(bytes/1048576).toFixed(2)} MB`,link:url,creditos:'Preservar créditos do autor original.'}};jobs.set(id,result);fs.rmSync(dir,{recursive:true,force:true});res.json(result)}catch(e){jobs.set(id,{id,status:'erro',error:e.message});fs.rmSync(dir,{recursive:true,force:true});res.status(400).json({ok:false,id,error:e.message})}});
app.get('/api/jobs/:id',(q,s)=>{const j=jobs.get(q.params.id);if(!j)return s.status(404).json({ok:false,error:'Análise não encontrada.'});s.json(j)});
app.listen(PORT,()=>console.log(`Fúria Mods IA V2.0 rodando na porta ${PORT}`));
